### ISSUE TITLE
Cakelisp code and GPL 3 license issues

### ISSUE THREAD

**Issue by Ilariel** [makuto/cakelisp#3]
Hi,

I'm not a lawyer so I'm not 100% sure whether these would be a real issue for end users, but I'm asking for clarification and possible changes. This is my interpretation of the current situation which might be wrong.

While the output code doesn't seem to be tainted by GPL3+ license there seems to be an issue with the Cakelisp files end users would write because compile-time code execution seems to require linking against code from the compiler which would most likely require end user code to be GPL licensed. Also does user code implicitly or explicitly use code from files in Runtime folder? 

Can we get a license exception for the Cakelisp interfacing/linking with the compiler during transpilation process? Something a kin to [LinkingOverControlledInterface](https://www.gnu.org/licenses/gpl-faq.en.html#LinkingOverControlledInterface)?

**Comment by makuto** [comment]
You've brought up some great points, and the link is very useful. I will update the license today. I'm going to make the runtime MIT, and clarify that the runtime isn't used unless the user explicitly requests it.

I'm also going to add the exception you linked so that compile-time code isn't forced to be GPL.
