### ISSUE TITLE
does Cakelisp has an AST

### ISSUE THREAD

**Issue by bentxt** [makuto/cakelisp#5]
I cannot find the section, but I think I've read somewhere that Cakelisp has no AST but uses "arrays of tokens" (or something similar). If that is true, could you elaborate on that?
thanks

**Comment by makuto** [comment]
Sure. The [Tokens](https://github.com/makuto/cakelisp/blob/master/doc/Cakelisp.org#tokens) section is where I said.

In S-expression languages, the user is so explicit that they are essentially writing the AST. In languages like C, the syntax needs to be parsed into an AST based on context.

In Cakelisp, characters in `.cake` files are tokenized into an `std::vector<Token>`. Once created, these arrays are marked `const` because various systems are allowed to refer directly to `Tokens` inside them via pointer, so the must not resize.

The generator `forward-declare` in [Macros.cake](https://github.com/makuto/cakelisp/blob/2193012e5fb24157fc07f2fe9e3bbf82b819e1fa/runtime/Macros.cake#L192) shows what iterating over the `tokens` array looks like. In this case, I did not need to make the algorithm recursive, because a simple depth counter sufficed for closing `namespace` blocks.

[Generators.cpp](https://github.com/makuto/cakelisp/blob/master/src/Generators.cpp) has tons of examples of how the tokens are interpreted to generate code, set compile-time settings, etc.

Essentially, the tokens are stored in flat arrays, but generators can decide to interpret them recursively when necessary. A recursive data structure like a tree isn't strictly necessary. My hope with using the contingent vector was better performance due to better cache locality (if you're evaluating token n+1, you are almost definitely going to evaluate token n+2 next, so if it's in an array, the cache will already have that token ready for you).

**Comment by bentxt** [comment]
> A recursive data structure like a tree isn't strictly necessary.

maybe I cannot see the big picture, but does that mean you that there is no lexical scoping?

**Comment by makuto** [comment]
Because Cakelisp transpiles to C, it relies on C's scoping rules. If you declare a var in a `when` or `scope`, that var will not be accessible outside that block.
