### ISSUE TITLE
question: Why is the compiler written in C++?

### ISSUE THREAD

**Issue by bentxt** [makuto/cakelisp#7]
Hi
Maybe these are even 2 questions:

- Why is the compiler written in C++ and not in a fast scripting language like a Scheme or a CL language?

- And second: why is the compiler not written in Cakelisp?

Thanks
Ben

**Comment by makuto** [comment]
- I'm most familiar with C and C++ because I'm a software engineer in the game industry. The familiarity made me more productive than any gains I would get from those other languages, because I don't know them well.

I wish I wrote Cakelisp in plain C, because that would make my self-modification goals easier to achieve. I may try to slowly convert it to C.

- I don't consider bootstrapping the language to be very valuable. Either way I have to distribute something that someone can build without having cakelisp already. The original language hasn't been much of a maintenance burden, so I don't think it's a liability.
